# Generated by Django 6.0.3 on 2026-03-19 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_anonyme', models.CharField(max_length=50, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre'), ('prefere_pas', 'Préfère ne pas préciser')], max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('situation', models.CharField(blank=True, choices=[('etudiant', 'Étudiant·e'), ('professionnel', 'Professionnel·le'), ('sans_emploi', 'Sans emploi'), ('retraite', 'Retraité·e'), ('autre', 'Autre')], max_length=20)),
                ('theme_couleur', models.CharField(choices=[('rose', 'Rose doux'), ('ocean', 'Océan calme'), ('foret', 'Forêt apaisante'), ('soleil', 'Soleil chaud'), ('nuit', 'Nuit étoilée')], default='rose', max_length=20)),
                ('comment_tu_te_sens', models.CharField(blank=True, choices=[('tres_bien', 'Très bien'), ('bien', 'Bien'), ('moyen', 'Moyen'), ('pas_bien', 'Pas très bien'), ('tres_mal', 'Vraiment mal')], max_length=20)),
                ('principales_difficultes', models.JSONField(blank=True, default=list)),
                ('objectif_principal', models.CharField(blank=True, max_length=200)),
                ('a_deja_consulte', models.BooleanField(blank=True, null=True)),
                ('niveau_urgence', models.IntegerField(choices=[(1, 'Je vais bien, je veux juste progresser'), (2, "Un peu d'anxiété ou de stress"), (3, 'Des difficultés modérées au quotidien'), (4, 'Des difficultés importantes'), (5, "En grande détresse, j'ai besoin d'aide maintenant")], default=1)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
