# Generated by Django 6.0.3 on 2026-07-08 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0005_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mon journal', max_length=100)),
                ('icon', models.CharField(default='📔', max_length=8)),
                ('color', models.CharField(choices=[('burgundy', 'burgundy'), ('forest', 'forest'), ('navy', 'navy'), ('mustard', 'mustard'), ('terracotta', 'terracotta'), ('plum', 'plum'), ('teal', 'teal'), ('charcoal', 'charcoal')], default='burgundy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('tres_mal', '😔 Vraiment mal'), ('pas_bien', '😟 Pas très bien'), ('neutre', '😐 Neutre'), ('bien', '🙂 Bien'), ('tres_bien', '😊 Très bien')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sanasource.journal')),
            ],
            options={
                'verbose_name': 'Entrée de journal',
                'verbose_name_plural': 'Entrées de journal',
                'ordering': ['entry_date'],
                'unique_together': {('journal', 'entry_date')},
            },
        ),
    ]
