# Generated by Django 6.0.3 on 2026-07-09 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0006_journal_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cover_style',
            field=models.CharField(choices=[('classic', 'Classique'), ('leather', 'Cuir'), ('linen', 'Lin'), ('floral', 'Fleuri'), ('kraft', 'Kraft'), ('velvet', 'Velours')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='JournalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('tres_mal', '😔 Vraiment mal'), ('pas_bien', '😟 Pas très bien'), ('neutre', '😐 Neutre'), ('bien', '🙂 Bien'), ('tres_bien', '😊 Très bien')], max_length=20)),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(blank=True, max_length=12)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sanasource.journal')),
            ],
            options={
                'verbose_name': 'Page de journal',
                'verbose_name_plural': 'Pages de journal',
                'ordering': ['page_number'],
                'unique_together': {('journal', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('sticker', 'Sticker'), ('drawing', 'Dessin'), ('voice_note', 'Note vocale')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='journal_attachments/%Y/%m/')),
                ('sticker_code', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sanasource.journalpage')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
