# Generated by Django 6.0.3 on 2026-07-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0007_journal_cover_style_journal_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attachment',
            name='position_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='attachment',
            name='position_y',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='attachment',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='width_pct',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('sticker', 'Sticker'), ('emoji', 'Emoji'), ('drawing', 'Dessin'), ('voice_note', 'Note vocale'), ('weather', 'Météo'), ('location', 'Lieu')], max_length=20),
        ),
    ]
