# Generated by Django 6.0.3 on 2026-07-09 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0008_attachment_label_attachment_position_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('love', 'Amour'), ('family', 'Famille'), ('childhood', 'Enfance'), ('anxiety', 'Anxiété'), ('dreams', 'Rêves'), ('career', 'Carrière'), ('self_esteem', 'Estime de soi'), ('personal_growth', 'Développement personnel')], max_length=20)),
                ('question', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('expiration_mode', models.CharField(choices=[('forever', 'Garder pour toujours'), ('24h', 'Supprimer après 24 heures'), ('7d', 'Supprimer après 7 jours'), ('30d', 'Supprimer après 30 jours'), ('on_read', 'Supprimer après la première lecture')], default='forever', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée — Brûler après écriture',
                'verbose_name_plural': 'Entrées — Brûler après écriture',
                'ordering': ['-created_at'],
            },
        ),
    ]
