# Generated by Django 6.0.3 on 2026-07-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0011_release_ritual'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personnel'), ('burn', 'Burn After Writing')], default='personal', max_length=10),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='release_ritual',
            field=models.CharField(blank=True, choices=[('fire', 'Feu')], max_length=20),
        ),
    ]
