# Generated by Django 6.0.3 on 2026-07-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0012_journal_kind_journalpage_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sana_nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
