# Generated by Django 6.0.3 on 2026-07-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0013_userprofile_has_seen_welcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/'),
        ),
    ]
