# Generated by Django 6.0.3 on 2026-07-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0015_newslettersubscriber_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notif_messages_communaute',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_nouveaux_articles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_rappels_humeur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_rappels_rdv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='priv_donnees_analytiques',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='priv_mode_anonyme',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='priv_partager_progres',
            field=models.BooleanField(default=True),
        ),
    ]
