# Generated by Django 6.0.3 on 2026-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0017_communitypost_supports_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Commentaire'), ('support', 'Soutien'), ('message', 'Message'), ('join', 'Rejoindre'), ('welcome', 'Bienvenue')], max_length=20),
        ),
    ]
