# Generated by Django 6.0.3 on 2026-07-11 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0018_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='requests_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('paypal', 'PayPal'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', "Arnaque / demande d'argent suspecte"), ('harassment', 'Harcèlement / propos violents'), ('spam', 'Spam'), ('inapproprie', 'Contenu inapproprié'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sanasource.communitypost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'reporter'), name='unique_report_per_user_per_post')],
            },
        ),
    ]
