# Generated by Django 6.0.3 on 2026-07-12 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0019_communitypost_is_reported_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('phq9', 'PHQ-9 (dépression)'), ('gad7', 'GAD-7 (anxiété)')], max_length=10)),
                ('score', models.PositiveSmallIntegerField()),
                ('band', models.CharField(max_length=50)),
                ('flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat auto-évaluation',
                'verbose_name_plural': 'Résultats auto-évaluation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedMyth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myth_text', models.TextField(max_length=500)),
                ('response_text', models.TextField(blank=True, max_length=1000)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_myths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mythe soumis',
                'verbose_name_plural': 'Mythes soumis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('checkin_dates', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression de défi',
                'verbose_name_plural': 'Progressions de défis',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge_id'), name='unique_challenge_per_user')],
            },
        ),
    ]
