# Generated by Django 6.0.3 on 2026-07-12 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0020_quizattempt_screeningresult_submittedmyth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_date', models.DateField()),
                ('reflection_text', models.TextField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Défi du jour complété',
                'verbose_name_plural': 'Défis du jour complétés',
                'ordering': ['-challenge_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userchallengeprogress',
            name='unique_challenge_per_user',
        ),
        migrations.AddField(
            model_name='dailychallengecompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userchallengeprogress',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='dailychallengecompletion',
            constraint=models.UniqueConstraint(fields=('user', 'challenge_date'), name='unique_daily_challenge_per_user_per_date'),
        ),
        migrations.DeleteModel(
            name='UserChallengeProgress',
        ),
    ]
