# Generated by Django 6.0.3 on 2026-07-12 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0021_dailychallengecompletion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('attrape-pensees', 'Attrape les pensées positives'), ('respire-avec-moi', 'Respire avec moi')], max_length=30)),
                ('score', models.PositiveSmallIntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partie jouée',
                'verbose_name_plural': 'Parties jouées',
                'ordering': ['-played_at'],
            },
        ),
    ]
