# Generated by Django 6.0.3 on 2026-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0022_gamesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game',
            field=models.CharField(choices=[('attrape_pensees', 'Attrape les pensées positives'), ('respire_avec_moi', 'Respire avec moi')], max_length=30),
        ),
    ]
