# Generated by Django 6.0.3 on 2026-07-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0024_alter_gamesession_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('finished', 'Terminé')], default='waiting', max_length=10)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('max_rounds', models.PositiveIntegerField(default=0)),
                ('current_emotion', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_game_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon de jeu',
                'verbose_name_plural': 'Salons de jeu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_system', models.BooleanField(default=False)),
                ('is_correct_guess', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sanasource.gameroom')),
            ],
            options={
                'verbose_name': 'Message de salon',
                'verbose_name_plural': 'Messages de salon',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('has_been_giver', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sanasource.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Joueur de salon',
                'verbose_name_plural': 'Joueurs de salon',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_player_per_room')],
            },
        ),
    ]
