# Generated by Django 6.0.3 on 2026-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0025_gameroom_gameroommessage_gameroomplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='ai_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
