# Generated by Django 6.0.3 on 2026-07-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0026_gameroom_ai_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WerewolfRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('night', 'Nuit'), ('day_discussion', 'Discussion'), ('day_vote', 'Vote'), ('finished', 'Terminé')], default='waiting', max_length=16)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('current_prompt', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(blank=True, choices=[('', ''), ('lumieres_win', 'Les Lumières ont gagné'), ('sombre_win', 'La Pensée Sombre a gagné')], default='', max_length=16)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_werewolf_rooms', to=settings.AUTH_USER_MODEL)),
                ('night_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon Ombre et Lumières',
                'verbose_name_plural': 'Salons Ombre et Lumières',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WerewolfMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sanasource.werewolfroom')),
            ],
            options={
                'verbose_name': 'Message Ombre et Lumières',
                'verbose_name_plural': 'Messages Ombre et Lumières',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WerewolfPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('lumiere', 'Pensée Lumineuse'), ('sombre', 'Pensée Sombre')], max_length=10)),
                ('is_alive', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='werewolf_room_memberships', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sanasource.werewolfroom')),
            ],
            options={
                'verbose_name': 'Joueur Ombre et Lumières',
                'verbose_name_plural': 'Joueurs Ombre et Lumières',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_werewolf_player_per_room')],
            },
        ),
        migrations.CreateModel(
            name='WerewolfVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sanasource.werewolfroom')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote Ombre et Lumières',
                'verbose_name_plural': 'Votes Ombre et Lumières',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'round_number', 'voter'), name='unique_vote_per_round')],
            },
        ),
    ]
