# Generated by Django 6.0.3 on 2026-07-12 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0027_werewolfroom_werewolfmessage_werewolfplayer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostorRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('discussion', 'Discussion'), ('vote', 'Vote'), ('finished', 'Terminé')], default='waiting', max_length=12)),
                ('secret_emotion', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(blank=True, choices=[('', ''), ('group_win', "Le groupe a démasqué l'Imposteur"), ('impostor_win', "L'Imposteur a échappé au vote")], default='', max_length=16)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_impostor_rooms', to=settings.AUTH_USER_MODEL)),
                ('impostor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon Imposteur des émotions',
                'verbose_name_plural': 'Salons Imposteur des émotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpostorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sanasource.impostorroom')),
            ],
            options={
                'verbose_name': 'Message Imposteur des émotions',
                'verbose_name_plural': 'Messages Imposteur des émotions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpostorPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impostor_room_memberships', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sanasource.impostorroom')),
            ],
            options={
                'verbose_name': 'Joueur Imposteur des émotions',
                'verbose_name_plural': 'Joueurs Imposteur des émotions',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_impostor_player_per_room')],
            },
        ),
        migrations.CreateModel(
            name='ImpostorVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sanasource.impostorroom')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote Imposteur des émotions',
                'verbose_name_plural': 'Votes Imposteur des émotions',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'voter'), name='unique_impostor_vote_per_room')],
            },
        ),
    ]
