# Generated by Django 6.0.3 on 2026-07-12 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0028_impostorroom_impostormessage_impostorplayer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Commentaire'), ('support', 'Soutien'), ('message', 'Message'), ('join', 'Rejoindre'), ('welcome', 'Bienvenue'), ('blog_winner', 'Blog élu')], max_length=20),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('astuce', 'Astuce anti-anxiété'), ('histoire', 'Histoire vécue'), ('autre', 'Autre réflexion')], default='astuce', max_length=12)),
                ('is_reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='saved_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sanasource.blogpost')),
            ],
            options={
                'verbose_name': 'Commentaire de blog',
                'verbose_name_plural': 'Commentaires de blog',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogWeeklyWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('likes_snapshot', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_weekly_wins', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_wins', to='sanasource.blogpost')),
            ],
            options={
                'verbose_name': 'Blog de la semaine',
                'verbose_name_plural': 'Blogs de la semaine',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='BlogYearlyWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('likes_snapshot', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_yearly_wins', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_wins', to='sanasource.blogpost')),
            ],
            options={
                'verbose_name': "Blog de l'année",
                'verbose_name_plural': "Blogs de l'année",
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harcèlement / propos violents'), ('spam', 'Spam'), ('inapproprie', 'Contenu inapproprié'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sanasource.blogpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement de blog',
                'verbose_name_plural': 'Signalements de blog',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'reporter'), name='unique_blog_report_per_user_per_post')],
            },
        ),
    ]
