# Generated by Django 6.0.3 on 2026-07-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanasource', '0029_alter_notification_type_blogpost_blogcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
