from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .forms import FrenchPasswordResetForm, FrenchSetPasswordForm

app_name = 'sanasource'
urlpatterns = [
    path('', views.page_open, name='page_open'),
    path('accueil/', views.accueil, name='accueil'),
    path('history/', views.history, name='history'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('help/', views.help_view, name='help'),
    path('logout/', views.logout_view, name='logout'),

    # ── Email verification ──
    path('verify-email/<uidb64>/<token>/', views.verify_email_view, name='verify_email'),
    path('verify-email/resend/', views.resend_verification_view, name='resend_verification'),

    # ── Password reset (Django's built-in views, French forms + our templates) ──
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='page/password_reset.html',
        email_template_name='email/password_reset_email.txt',
        subject_template_name='email/password_reset_subject.txt',
        form_class=FrenchPasswordResetForm,
        success_url=reverse_lazy('sanasource:password_reset_done'),
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='page/password_reset_done.html',
    ), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='page/password_reset_confirm.html',
        form_class=FrenchSetPasswordForm,
        success_url=reverse_lazy('sanasource:password_reset_complete'),
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='page/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('api/chat/', views.sana_chat, name='sana_chat'),
    path('api/conversations/', views.conversations_api, name='conversations_api'),
    path('api/conversations/<int:conversation_id>/', views.conversation_detail_api, name='conversation_detail_api'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('groupes/', views.group_page, name='group_page'),
    path('api/groupes/creer/', views.create_group, name='create_group'),
    path('api/groupes/<int:group_id>/membres/', views.join_leave_group, name='join_leave_group'),
    path('api/groupes/<int:group_id>/messages/', views.group_messages_api, name='group_messages_api'),
    path('api/humeur/', views.save_mood, name='save_mood'),
    path('journal/', views.journal_home, name='journal_home'),
    path('journal/personnel/', views.journal_bookshelf, name='journal_bookshelf'),
    path('journal/burn/', views.journal_burn_open, name='journal_burn_open'),
    path('journal/<int:journal_id>/', views.journal_book, name='journal_book'),
    path('api/journal/', views.journals_api, name='journals_api'),
    path('api/journal/<int:journal_id>/', views.journal_detail_api, name='journal_detail_api'),
    path('api/journal/<int:journal_id>/duplicate/', views.journal_duplicate_api, name='journal_duplicate_api'),
    path('api/journal/<int:journal_id>/dates/', views.journal_dates_api, name='journal_dates_api'),
    path('api/journal/<int:journal_id>/entry/<str:date_str>/', views.journal_entry_api, name='journal_entry_api'),
    path('api/journal/<int:journal_id>/pages/', views.journal_pages_list_api, name='journal_pages_list_api'),
    path('api/journal/<int:journal_id>/page/by-date/<str:date_str>/', views.journal_page_by_date_api, name='journal_page_by_date_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/next/', views.journal_page_next_api, name='journal_page_next_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/attachments/', views.journal_page_attachments_api, name='journal_page_attachments_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/attachments/<int:attachment_id>/', views.journal_attachment_detail_api, name='journal_attachment_detail_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/archive/', views.journal_page_archive_api, name='journal_page_archive_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/lock/', views.journal_page_lock_api, name='journal_page_lock_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/release/', views.journal_page_release_api, name='journal_page_release_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/disposition/', views.journal_page_disposition_api, name='journal_page_disposition_api'),
    path('api/journal/<int:journal_id>/page/<int:page_number>/', views.journal_page_api, name='journal_page_api'),
    path('api/communaute/', views.community_post_api, name='community_post_api'),
    path('api/communaute/<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('api/communaute/<int:post_id>/soutenir/', views.toggle_support, name='toggle_support'),
    path('api/communaute/<int:post_id>/paiement/', views.post_payment_info, name='post_payment_info'),
    path('api/communaute/<int:post_id>/signaler/', views.report_post, name='report_post'),
    path('api/communaute/<int:post_id>/commentaires/', views.post_comments_api, name='post_comments_api'),
    path('api/avis/', views.submit_review, name='submit_review'),
    path('newsletter/subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('newsletter/confirm/<str:token>/', views.newsletter_confirm, name='newsletter_confirm'),
    path('newsletter/unsubscribe/<str:token>/', views.newsletter_unsubscribe, name='newsletter_unsubscribe'),
    path('api/settings/', views.update_setting, name='update_setting'),
    path('api/profile/', views.update_profile, name='update_profile'),
    path('api/notifications/', views.notifications_api, name='notifications_api'),
    path('api/notifications/<int:notif_id>/read/', views.notification_read, name='notification_read'),
    path('api/push/subscribe/', views.push_subscribe, name='push_subscribe'),
    path('api/push/unsubscribe/', views.push_unsubscribe, name='push_unsubscribe'),
    path('api/notifications/unread/', views.notifications_unread_count, name='notifications_unread'),
    path('messages/<int:user_id>/', views.dm_page, name='dm_page'),
    path('api/dm/', views.dm_conversations, name='dm_conversations'),
    path('api/dm/<int:user_id>/', views.dm_api, name='dm_api'),
]